/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "IP Address": {                                  "en": "IP Address",                                      "de": "IP-Adresse",                                      "ru": "Айпи адрес",                                      "pt": "Endereço de IP",                                  "nl": "IP adres",                                        "fr": "Adress IP",                                       "it": "Indirizzo IP",                                    "es": "Dirección IP",                                    "pl": "Adres IP",                                        "zh-cn": "IP地址"},
    "Ping interval": {                               "en": "Interval to ping the realtime connection in sec, (0=none)", "de": "Intervall zum Pingen der Echtzeitverbindung in Sekunden (0 = keine)", "ru": "Интервал проверки связи в реальном времени в секундах (0 = нет)", "pt": "Intervalo para executar ping na conexão em tempo real em segundos, (0 = nenhum)", "nl": "Interval om de realtime verbinding in seconden te pingen, (0 = geen)", "fr": "Intervalle de ping de la connexion en temps réel en sec, (0 = aucun)", "it": "Intervallo per eseguire il ping della connessione in tempo reale in secondi, (0 = nessuno)", "es": "Intervalo para hacer ping a la conexión en tiempo real en segundos, (0 = ninguno)", "pl": "Interwał pingowania połączenia w czasie rzeczywistym w sekundach (0 = brak)", "zh-cn": "ping实时连接的时间间隔，以秒为单位，（0 =无）"},
    "Poll Interval": {                               "en": "Poll Interval",                                   "de": "Abfrageintervall",                                "ru": "Интервал опроса",                                 "pt": "Intervalo de votação",                            "nl": "Pollinterval",                                    "fr": "Intervalle de sondage",                           "it": "Intervallo di polling",                           "es": "Intervalo de encuesta",                           "pl": "Interwał sondowania",                             "zh-cn": "轮询间隔"},
    "Realtime Options": {                            "en": "Realtime Options",                                "de": "Echtzeitoptionen",                                "ru": "Варианты в реальном времени",                     "pt": "Opções em tempo real",                            "nl": "Realtime opties",                                 "fr": "Options en temps réel",                           "it": "Opzioni in tempo reale",                          "es": "Opciones en tiempo real",                         "pl": "Opcje w czasie rzeczywistym",                     "zh-cn": "实时选项"},
    "Use Realtime": {                                "en": "Use Realtime",                                    "de": "Echtzeitmodus verwenden",                         "ru": "Использовать в реальном времени",                 "pt": "Usar em tempo real",                              "nl": "Gebruik Realtime",                                "fr": "Utiliser en temps réel",                          "it": "Usa in tempo reale",                              "es": "Usar en tiempo real",                             "pl": "Użyj czasu rzeczywistego",                        "zh-cn": "使用实时"},
    "refreshOnRealtime": {                           "en": "Refresh all states on realtime event",            "de": "Aktualisieren Sie alle Datenpunkte bei einem Echtzeitereignis", "ru": "Обновить все точки данных на событии в реальном времени", "pt": "Atualizar todos os pontos de dados no evento em tempo real", "nl": "Ververs alle datapunten op een realtime evenement", "fr": "Actualisez tous les points de données sur l'événement en temps réel", "it": "Aggiorna tutti i punti dati sull'evento in tempo reale", "es": "Actualizar todos los puntos de datos en un evento en tiempo real", "pl": "Odśwież wszystkie punkty danych podczas wydarzenia w czasie rzeczywistym", "zh-cn": "在实时事件上刷新所有数据点"},
    "template adapter settings": {                   "en": "Adapter settings for template",                   "de": "Adaptereinstellungen für template",               "ru": "Настройки адаптера для template",                 "pt": "Configurações do adaptador para template",        "nl": "Adapterinstellingen voor template",               "fr": "Paramètres d'adaptateur pour template",           "it": "Impostazioni dell'adattatore per template",       "es": "Ajustes del adaptador para template",             "pl": "Ustawienia adaptera dla template",                "zh-cn": "template的适配器设置"},
};